function model = calcModelEnergy(country, model)

% functions now combined in this one function: 
% model = calcEnergyBreakdown(country, model);
% model = calcEnergyCosts(country, model);
% model = calcFossilFuelEmissions(country, model);
% model = calcWaterRequiredEnergy(country, model);

%% function model = calcEnergyBreakdown(country,model)

% FUNCTION: calcEnergyBreakdown

% INPUTS:
% - country: the table of values associated with the countries
% - model: the table of values associated with the model
%   note: expected that both "Total Energy Demand" and "Percent Energy from Renewable"
%         have already been set in the model
% OUTPUTS:
% - model: the updated table of values associated with the model
%   note: see calculations performed for new model values created

% CALCULATIONS PERFORMED:
%   based on the "Total Energy Demand", "Percent Energy from Renewable", and various
%   default country information (e.g. "Existing Renewable Capacity"), generate the following:
% - "Amount Energy from Existing Renewable": the amount of energy generated by/from exisiting renewable capabilities
% - "Amount Energy from New Renewable": the amount of energy generated by/from new renewable sources (developed via investment)
% - "Amount Energy from Fossil Fuel": the amount of energy generated by/from fossil fuel sources (aka "everything else" that's not renewable)

% returns energy breakdown of countries a and b where energy is either
% from fossil fuels, existing renewable energy, or new renewable energy

% how much total renewable energy is needed
model.Renew_Energy_Tot = model.Pct_Energy_fr_Renew .* model.Tot_Energy_Demand;

% the amount of fossil fuel is "everything not geneated by renewable", so calculate this based on total energy demand
model.Amt_Energy_fr_FF = model.Tot_Energy_Demand - model.Renew_Energy_Tot;

% need to know capacity: country.Exist_Renew_Energy_Capac
% and what you want from renewables: model.Renew_Energy_Tot
% check if the amount of renewable you want is above current capacity
% if it's above the capacity, then set the amount from existing at the capacity
% if it's below the capacity, then set it at the existing amt.

% check each country one at a time 
for i = 1:2
    if model.Renew_Energy_Tot(i) > country.Exist_Renew_Energy_Capac(i)
        model.Amt_Energy_fr_Exist_Renew(i) = country.Exist_Renew_Energy_Capac(i);
    else
        model.Amt_Energy_fr_Exist_Renew(i) = model.Renew_Energy_Tot(i);
    end
end


% the INVESTMENT amount (New Renewable) is any renewable energy that is not generated by "Existing Renewable Capacity"
model.Amt_Energy_fr_New_Renew = model.Renew_Energy_Tot - model.Amt_Energy_fr_Exist_Renew;



%% function model = calcEnergyCosts(country,model)

% FUNCTION: calcEnergyCosts
% INPUTS:
% - country: table associated with the countries
% - model: table associated with the model
%   note: expected that "Amount Energy from Existing Renewable", "Amount Energy from New Renewable",
%   and "Amount Energy from Fossil Fuel" have been created within the model
% OUTPUTS:
% - model: the updated table of values associated with the model
%   note: see calculations performed for new model values created
% CALCULATIONS PERFORMED:
%   based on various energy amounts, as well as the cost-per-energy units from the country data,
%   calculate the following and add the values to the model:
% - "Cost Energy from Existing Renewable": cost of renewable energy generated by existing capabilities (in $USD)
% - "Cost Energy from New Renewable": cost of renewable energy generated via new sources, developed via investment in renewable energy (in $USD)
% - "Cost Energy from Fossil Fuel": cost of energy generated via fossil fuel (in $USD)
% - "Cost Energy Total": TOTAL cost of energy across all three sources (in $USD)

model.Cost_Energy_fr_Exist_Renew = model.Amt_Energy_fr_Exist_Renew .* country.ECR_Energy_fr_Exist_Renew;
model.Cost_Energy_fr_New_Renew = model.Amt_Energy_fr_New_Renew .* country.ECR_Energy_fr_New_Renew;
model.Cost_Energy_fr_FF = model.Amt_Energy_fr_FF .* country.ECR_Energy_fr_FF;
model.Cost_Energy_Tot = model.Cost_Energy_fr_Exist_Renew + model.Cost_Energy_fr_New_Renew + model.Cost_Energy_fr_FF;


%% function model = calcFossilFuelEmissions(country, model)

emissions_conversion = 0.000388; % it is 0.000388 metric tons (mt) of CO2 per kWh
% note: divide by 10-to-the-6th to convert metric tons (mt) to million metric tons (Mt)

model.FF_Emissions = model.Amt_Energy_fr_FF .* emissions_conversion;


%% function model = calcWaterRequiredEnergy(country, model)

% INPUTS:
% - fossil_fuel_amount: energy amount produced by fossil fuel sources, in Kilowatt hours (kWh)
% OUTPUTS:
% - water_required_energy: amount of water required for energy production (in Cubic Kilometer, or Km^3)

model.Water_Reqd_Energy = model.Amt_Energy_fr_FF .* country.WRC_Energy_FF;

